config/routes.rb
List::Application.routes.draw do
  devise_for :users

  resources :tasks

  resources :categories

  resources :categories_orders

  resources :tasks_orders

  resources :auto_complate

  devise_scope :user do
    get "/" => "devise/registrations#new"
  end

end

app/models/task.rb
class Task
  include Mongoid::Document

  field :title, type: String
  field :description, type: String
  field :category_id, type: Integer
  field :user_id, type: Integer

  attr_accessible :description, :title, :category_id, :user_id, :category
  belongs_to :category
  belongs_to :user
  validate :title_or_description

  def self.ordered_by_tasks(logged_in_user, category_id)
    if category_id
      order = logged_in_user.categories.find(category_id).category_tasks_order || []
      new_order = []
      order.each do |o|
        logged_in_user.categories.find(category_id).tasks.find(o) ? new_order << logged_in_user.categories.find(category_id).tasks.find(o) : o
      end
      new_order + (logged_in_user.categories.find(category_id).tasks - new_order)
    else
      order = logged_in_user.all_tasks_order || []
      new_order = []
      order.each do |o|
        logged_in_user.tasks.find(o) ? new_order << logged_in_user.tasks.find(o) : o
      end
      new_order + (logged_in_user.tasks - new_order)
    end
  end


  private

  def title_or_description
    self.errors.add(:title, 'title or description should be specified') if title.blank? && description.blank?
  end

  def category_name
    category.name
  end

  def category_name(name)
     self.category = Category.find_or_create_by_name(name) unless name.blank?
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :find_tasks, :only => [:index]

  def index
  end

  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  def new
    if current_user.categories == []
      redirect_to tasks_path, notice: 'Not fount category!'
    else
      @task = Task.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @task }
      end
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(params[:task])
    @task.user = current_user
    find_tasks
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.js { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.js { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    find_tasks
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end

  private

  def find_tasks
    @tasks = Task.ordered_by_tasks(current_user, params[:category_id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.slim
= form_for(@task) do |f|
  - if @task.errors.any?
    div id="error_explanation"
      h2
        = pluralize(@task.errors.count, "error")
        = " "
        | prohibited this task from being saved:

      ul
        - @task.errors.full_messages.each do |msg|
          li
            = msg

  div class="field"
    = f.label :title
    br
    = f.text_field :title
  div class="field"
    = f.label :description
    br
    = f.text_field :description
  div class="field"
    = f.label :category
    br
    div
        = f.text_field :category, {:id => "search", :url => auto_complate_index_path(:js), :method => :get}
  div class="actions"
    = f.submit

app/views/tasks/_sortable_tasks.html.slim
p id="notice"
  = notice

div id="task_ol"
  div class="title"
    div id="id1" №
    div id="id1" Title
    div id="id1" Description

  div
    = hidden_field_tag :category_id, '', value: params[:category_id]
    ol class="sortable"
      - @tasks.each do |task|
          li class="line" id="task_#{cycle(task.id)}"
            div
              = task.title
            div
              = task.description
            div class="v"
              = link_to image_tag("srch_24.png"), task
            div class="v" id="icon2"
              = link_to image_tag("tools_24.png"), edit_task_path(task)
            div class="v" id="icon3"
              = link_to image_tag("trash_24.png"), task, method: :delete, data: {confirm: 'Are you sure?'}, :remote => true

javascript:
    $(function() {
        $(".sortable").sortable({
            update: function(event, ui) {
                var str = $(this).sortable('serialize');
                if ($('#category_id').val()) {
                  str = str + "&category_id=" + $('#category_id').val();
                }
                $.ajax({
                    url: '#{tasks_orders_path}',
                    data: str
                });
            }
        })
    });

app/views/tasks/destroy.js.slim
| $("#task_#{@task.id}").remove()

app/views/tasks/edit.html.slim
h1
  Editing task

= render 'form'

= link_to 'Show', @task
= " "
= link_to 'Back', tasks_path

app/views/tasks/index.html.slim
h1
  Listing tasks

div
  = render :partial => "sortable_tasks.html"

a href="/tasks/new" Add new task

app/views/tasks/new.html.slim
h1
  New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.slim
p id="notice"
  = notice

p
  b Title:
  = @task.title

p
  b Description:
  = @task.description


= link_to 'Edit', edit_task_path(@task)
=" "
= link_to 'Back', tasks_path