config/routes.rb
List::Application.routes.draw do
  devise_for :users

  resources :tasks

  resources :categories

  resources :categories_orders

  resources :tasks_orders

  resources :auto_complate

  devise_scope :user do
    get "/" => "devise/registrations#new"
  end

end

app/models/category.rb
class Category

  include Mongoid::Document

  field :name, type: String
  field :user_id, type: Integer
  field :category_tasks_order, type: Array
  include Mongoid::Document


  attr_accessible :name, :user_id, :category_tasks_order, :user
  belongs_to :user
  has_many :tasks
  validates :name, :presence => true

  def hi(user)
    user.full_name
  end

  def self.ordered_by_categories(logged_in_user)
    order = logged_in_user.categories_order || []
    new_order = []
    order.each do |o|
      logged_in_user.categories.find(o) ? new_order << logged_in_user.categories.find(o) : o
    end
    new_order + (logged_in_user.categories - new_order)
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :find_categories, :only => [:index]

  def index

    @category = Category.new

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])
    @category.user = current_user
    respond_to do |format|
      if @category.save
        find_categories
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.js
      else                                      categort
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    find_categories
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.js
    end
  end

  private

  def find_categories
    @categories = Category.ordered_by_categories(current_user)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
= form_for(@category, :remote => true) do |f|
  - if @category.errors.any?
    div id="error_explanation"
      h2
        = pluralize(@category.errors.count, "error")
        = " "
        | prohibited this category from being saved:
      ul
        - @category.errors.full_messages.each do |msg|
          li
            = msg

  div class="field"
    = f.label :name
    br
    = f.text_field :name
  div class="actions"
    = f.submit

app/views/categories/_li_sortable.html.slim
div id="category_ol"
  div class="title"
    div id="id1" №
    div id="id1" Category

  div
    ol class="sortable"
      - @categories.each do |category|
          li class="line" id="category_#{category.id}"
            div
              = link_to category.name, tasks_path(:category_id => category)
            div class="v"
              = link_to image_tag("srch_24.png"), category
            div class="v" id="icon2"
              = link_to image_tag("tools_24.png"), edit_category_path(category)
            div class="v" id="icon3"
              = link_to image_tag("trash_24.png"), category, method: :delete, data: {confirm: 'Are you sure?'}, :remote => true

javascript:
    $(function() {
        $(".sortable").sortable({
            update: function(event, ui) {
                var str=$(this).sortable('serialize');
                $.ajax({
                    url: "#{categories_orders_path}",
                    data: str
                });
            }
        })
    });

app/views/categories/_mypage.html.slim
div id="tabs"
  ul
    li: a href="#tabs-1" Messages
    li: a href="#tabs-2" Requests
    li: a href="#tabs-3" Notifications
    li: a href="#tabs-4" Suggested Users
  div id="tabs-1"
    | lsdkjfgdfklsgdflsgndflsgnjdflgj
  div id="tabs-2"
    | dfngdfsngdkfgdflskgdflgdflg
  div id="tabs-3"
    | dksfjghkdsfgdfkjghdsfkjghdskjg
  div id="tabs-4"
    | jgljdfslgjdfjsgdfklsgj


javascript:
    $(function() {
        $( "#tabs" ).tabs();
    });

app/views/categories/create.js.slim
| $('#category_ol').replaceWith('#{escape_javascript(render(:partial => 'li_sortable.html', :locals => { :categories => @categories }))}');
| $("form input[type=text]").val('');

app/views/categories/destroy.js.slim
| $('#category_ol').replaceWith('#{escape_javascript(render(:partial => 'li_sortable.html', :locals => { :categories => @categories }))}');

app/views/categories/edit.html.slim
h1 Editing category

= render 'form'

= link_to 'Show', @category
= " "
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 New category

= render 'form'

br

h1 Listing categories

div
    = render :partial => 'li_sortable.html'

app/views/categories/new.html.slim
h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
p id="notice"
  = notice

p
  b Name:
  = @category.name



= link_to 'Edit', edit_category_path(@category)
= " "
= link_to 'Back', categories_path