config/routes.rb
List::Application.routes.draw do
  devise_for :users

  resources :tasks

  resources :categories

  resources :categories_orders

  resources :tasks_orders

  resources :auto_complate

  devise_scope :user do
    get "/" => "devise/registrations#new"
  end

end

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
    head
      title List
      = stylesheet_link_tag "application2", :media => "all"
      = javascript_include_tag "application"
      = csrf_meta_tags


    body
        div class="main"
          div class="textmenu"
            - if current_user
                div
                  | Login:
                  = current_user.email
                  = link_to 'Log Out', destroy_user_session_path, :method => :delete
            - else
                div
                  = render "new_session"

          div class="topmenu"
            ul
              li: a href="/categories/" Gategories
              li: a href="/tasks/" Tasks

          div class="categories"
            - if current_user
                = yield
            - else
               | Registered pleas

app/views/layouts/start_page.html.slim
<!DOCTYPE html>
html
    head
      title Hello! This is start page
      = stylesheet_link_tag "start_page", :media => "all"
      = javascript_include_tag "start_page"
      = csrf_meta_tags

    body
        div class="main"
          div class="top"
            div
              h1 ByMeterSoft
            div
              = link_to "Sign up", new_registration_path(resource_name)

          div class="textmenu"
            = render "devise/sessions/new_session"

          div class="panel"
            h1 Welcome!
            = yield